<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="18803" started-at="2016-01-07T12:34:59Z" finished-at="2016-01-07T12:35:18Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="18803" started-at="2016-01-07T12:34:59Z" finished-at="2016-01-07T12:35:18Z">
      <class name="tests.Validate_ParticipantHomePage">
        <test-method status="PASS" signature="InitTest()[pri:0, instance:tests.Validate_ParticipantHomePage@11fa9dd]" name="InitTest" is-config="true" duration-ms="18353" started-at="2016-01-07T12:34:59Z" finished-at="2016-01-07T12:35:18Z">
        </test-method> <!-- InitTest -->
        <test-method status="FAIL" signature="f(int, java.util.Map)[pri:0, instance:tests.Validate_ParticipantHomePage@11fa9dd]" name="f" duration-ms="15" started-at="2016-01-07T12:35:18Z" data-provider="setData" finished-at="2016-01-07T12:35:18Z">
          <exception class="org.testng.TestNGException">
            <message>
              <![CDATA[
The data provider is trying to pass 0 parameters but the method tests.Validate_ParticipantHomePage#f takes 2 and TestNG is unable in inject a suitable object]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestNGException: 
The data provider is trying to pass 0 parameters but the method tests.Validate_ParticipantHomePage#f takes 2 and TestNG is unable in inject a suitable object
	at org.testng.internal.Invoker.injectParameters(Invoker.java:1349)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1213)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:768)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1188)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1113)
	at org.testng.TestNG.run(TestNG.java:1025)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
	at org.testng.internal.Invoker.injectParameters(Invoker.java:1347)
	... 17 more
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestNGException -->
        </test-method> <!-- f -->
        <test-method status="PASS" signature="tear()[pri:0, instance:tests.Validate_ParticipantHomePage@11fa9dd]" name="tear" is-config="true" duration-ms="418" started-at="2016-01-07T12:35:18Z" finished-at="2016-01-07T12:35:18Z">
        </test-method> <!-- tear -->
      </class> <!-- tests.Validate_ParticipantHomePage -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
