<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="XWJPMDD085" name="app.csas.testcases.loanRequest.LoanRequestTestCases" tests="41" failures="8" timestamp="15 Feb 2018 03:18:59 GMT" time="2566.045" errors="26">
  <testcase name="CSAS_Paperless_Loan_TC04_DDTC_26942" time="66.792" classname="app.csas.testcases.loanRequest.LoanRequestTestCases"/>
  <testcase name="validating_mobile_phone_text_box" time="60.704" classname="app.csas.testcases.loanRequest.LoanRequestTestCases">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at pageobjects.LoanRequest.isLoaded(LoanRequest.java:536)
	at org.openqa.selenium.support.ui.LoadableComponent.get(LoadableComponent.java:52)
	at app.csas.testcases.loanRequest.LoanRequestTestCases.validating_mobile_phone_text_box(LoanRequestTestCases.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- validating_mobile_phone_text_box -->
  <testcase name="DDTC_25968_Paperless_Loan_Exceptions" time="65.560" classname="app.csas.testcases.loanRequest.LoanRequestTestCases"/>
  <testcase name="DDTC_26931_Paperless_Loan_Exceptions" time="64.941" classname="app.csas.testcases.loanRequest.LoanRequestTestCases"/>
  <testcase name="DDTC_26926_Paperless_Loan_Exceptions" time="87.903" classname="app.csas.testcases.loanRequest.LoanRequestTestCases"/>
  <testcase name="CSAS_Paperless_Loan_TC10_DDTC_26925" time="67.019" classname="app.csas.testcases.loanRequest.LoanRequestTestCases"/>
  <testcase name="validating_vesting_field" time="60.592" classname="app.csas.testcases.loanRequest.LoanRequestTestCases">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at pageobjects.LoanRequest.isLoaded(LoanRequest.java:536)
	at org.openqa.selenium.support.ui.LoadableComponent.get(LoadableComponent.java:52)
	at app.csas.testcases.loanRequest.LoanRequestTestCases.validating_vesting_field(LoanRequestTestCases.java:178)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- validating_vesting_field -->
  <testcase name="CSAS_Paperless_Loan_TC08_DDTC_26084" time="66.972" classname="app.csas.testcases.loanRequest.LoanRequestTestCases"/>
  <testcase name="DDTC_25966_Paperless_Loan_Exceptions" time="58.556" classname="app.csas.testcases.loanRequest.LoanRequestTestCases"/>
  <testcase name="validating_loan_number_link" time="61.192" classname="app.csas.testcases.loanRequest.LoanRequestTestCases">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at pageobjects.LoanRequest.isLoaded(LoanRequest.java:536)
	at org.openqa.selenium.support.ui.LoadableComponent.get(LoadableComponent.java:52)
	at app.csas.testcases.loanRequest.LoanRequestTestCases.validating_loan_number_link(LoanRequestTestCases.java:92)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- validating_loan_number_link -->
  <testcase name="CSAS_Paperless_Loan_LoanRequest_TC32_DDTC_24267" time="66.707" classname="app.csas.testcases.loanRequest.LoanRequestTestCases"/>
  <testcase name="CSAS_Paperless_Loan_LoanRequest_Back_Hyperlink_TC20_DDTC_24665" time="66.612" classname="app.csas.testcases.loanRequest.LoanRequestTestCases"/>
  <testcase name="CSAS_Paperless_Loan_Exceptions_TC12_DDTC_26082" time="66.814" classname="app.csas.testcases.loanRequest.LoanRequestTestCases"/>
  <testcase name="CSAS_Paperless_Loan_LoanRequest_TC36_DDTC_24264" time="66.659" classname="app.csas.testcases.loanRequest.LoanRequestTestCases"/>
  <testcase name="CSAS_Paperless_Loan_LoanRequest_TC34_DDTC_24266" time="66.622" classname="app.csas.testcases.loanRequest.LoanRequestTestCases"/>
  <testcase name="CSAS_Paperless_Loan_LoanRequest_TC24_DDTC_26088" time="66.762" classname="app.csas.testcases.loanRequest.LoanRequestTestCases"/>
  <testcase name="DDTC_25959_Paperless_Loan_Exceptions" time="34.224" classname="app.csas.testcases.loanRequest.LoanRequestTestCases"/>
  <testcase name="CSAS_Paperless_Loan_LoanRequest_TC22_DDTC_26093" time="67.189" classname="app.csas.testcases.loanRequest.LoanRequestTestCases"/>
  <testcase name="CSAS_Paperless_Loan_HappyPath_TC18_DDTC_27976" time="66.812" classname="app.csas.testcases.loanRequest.LoanRequestTestCases"/>
  <testcase name="CSAS_Paperless_Loan_LoanRequest_TC30_DDTC_24268" time="66.842" classname="app.csas.testcases.loanRequest.LoanRequestTestCases"/>
  <testcase name="CSAS_Paperless_Loan_LoanRequest_TC38_DDTC_24262" time="66.906" classname="app.csas.testcases.loanRequest.LoanRequestTestCases"/>
  <testcase name="DDTC_26089_Paperless_Loan_Exceptions" time="33.516" classname="app.csas.testcases.loanRequest.LoanRequestTestCases"/>
  <testcase name="DDTC_25965_Paperless_Loan_Exceptions" time="62.651" classname="app.csas.testcases.loanRequest.LoanRequestTestCases"/>
  <testcase name="DDTC_24263_PaperlessLoan_LoanStructureOverviewSection_4" time="42.158" classname="app.csas.testcases.loanRequest.LoanRequestTestCases"/>
  <testcase name="validating_green_tick_on_selection_of_loan_quote" time="60.528" classname="app.csas.testcases.loanRequest.LoanRequestTestCases">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at pageobjects.LoanRequest.isLoaded(LoanRequest.java:536)
	at org.openqa.selenium.support.ui.LoadableComponent.get(LoadableComponent.java:52)
	at app.csas.testcases.loanRequest.LoanRequestTestCases.validating_green_tick_on_selection_of_loan_quote(LoanRequestTestCases.java:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- validating_green_tick_on_selection_of_loan_quote -->
  <testcase name="CSAS_Paperless_Loan_TC02_DDTC_26947" time="67.301" classname="app.csas.testcases.loanRequest.LoanRequestTestCases"/>
  <testcase name="DDTC_25970_Paperless_Loan_Exceptions" time="61.246" classname="app.csas.testcases.loanRequest.LoanRequestTestCases"/>
  <testcase name="CSAS_Paperless_Loan_HappyPath_TC16_DDTC_27971" time="67.212" classname="app.csas.testcases.loanRequest.LoanRequestTestCases"/>
  <testcase name="validating_if_payment_method_noneditable" time="60.614" classname="app.csas.testcases.loanRequest.LoanRequestTestCases">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at pageobjects.LoanRequest.isLoaded(LoanRequest.java:536)
	at org.openqa.selenium.support.ui.LoadableComponent.get(LoadableComponent.java:52)
	at app.csas.testcases.loanRequest.LoanRequestTestCases.validating_if_payment_method_noneditable(LoanRequestTestCases.java:158)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- validating_if_payment_method_noneditable -->
  <testcase name="DDTC_25950_Paperless_Loan_Exceptions" time="48.750" classname="app.csas.testcases.loanRequest.LoanRequestTestCases"/>
  <testcase name="CSAS_Paperless_Loan_LoanRequest_TC28_DDTC_26080" time="66.707" classname="app.csas.testcases.loanRequest.LoanRequestTestCases"/>
  <testcase name="validating_recalculate_functionality" time="61.009" classname="app.csas.testcases.loanRequest.LoanRequestTestCases">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at pageobjects.LoanRequest.isLoaded(LoanRequest.java:536)
	at org.openqa.selenium.support.ui.LoadableComponent.get(LoadableComponent.java:52)
	at app.csas.testcases.loanRequest.LoanRequestTestCases.validating_recalculate_functionality(LoanRequestTestCases.java:200)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- validating_recalculate_functionality -->
  <testcase name="CSAS_Paperless_Loan_HappyPath_TC14_DDTC_27970" time="67.364" classname="app.csas.testcases.loanRequest.LoanRequestTestCases"/>
  <testcase name="DDTC_26960_DDTC_26945_Paperless_LoanPaymentFrequenct_PaymentMethod" time="79.159" classname="app.csas.testcases.loanRequest.LoanRequestTestCases"/>
  <testcase name="DDTC_25954_Paperless_Loan_Exceptions" time="37.758" classname="app.csas.testcases.loanRequest.LoanRequestTestCases"/>
  <testcase name="CSAS_Paperless_Loan_TC06_DDTC_26083" time="67.517" classname="app.csas.testcases.loanRequest.LoanRequestTestCases"/>
  <testcase name="statement_order_update_confirmation" time="60.591" classname="app.csas.testcases.loanRequest.LoanRequestTestCases">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at pageobjects.LoanRequest.isLoaded(LoanRequest.java:536)
	at org.openqa.selenium.support.ui.LoadableComponent.get(LoadableComponent.java:52)
	at pageobjects.Statement_View_Update.load(Statement_View_Update.java:207)
	at org.openqa.selenium.support.ui.LoadableComponent.get(LoadableComponent.java:49)
	at app.csas.testcases.loanRequest.LoanRequestTestCases.statement_order_update_confirmation(LoanRequestTestCases.java:132)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- statement_order_update_confirmation -->
  <testcase name="CSAS_Paperless_Loan_LoanRequest_TC26_DDTC_26085" time="66.747" classname="app.csas.testcases.loanRequest.LoanRequestTestCases"/>
  <testcase name="validating_refinance_with_adtn_loan_amnt_functionality" time="60.513" classname="app.csas.testcases.loanRequest.LoanRequestTestCases">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at pageobjects.LoanRequest.isLoaded(LoanRequest.java:536)
	at org.openqa.selenium.support.ui.LoadableComponent.get(LoadableComponent.java:52)
	at app.csas.testcases.loanRequest.LoanRequestTestCases.validating_refinance_with_adtn_loan_amnt_functionality(LoanRequestTestCases.java:242)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- validating_refinance_with_adtn_loan_amnt_functionality -->
  <testcase name="DDTC_25952_Paperless_Loan_Exceptions" time="65.452" classname="app.csas.testcases.loanRequest.LoanRequestTestCases"/>
  <testcase name="DDTC_25963_Paperless_Loan_Exceptions" time="66.872" classname="app.csas.testcases.loanRequest.LoanRequestTestCases"/>
</testsuite> <!-- app.csas.testcases.loanRequest.LoanRequestTestCases -->
