<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="xdjpmdd089" name="Default test" tests="1" failures="1" timestamp="19 Jan 2016 09:32:13 GMT" time="17.9" errors="0">
  <testcase name="Validate_Employment_Status_As_Active_Or_Terminated" time="0.109" classname="app.csas.testcases.participanthomepage.validate_participanthomepage">
    <failure type="org.testng.TestNGException" message="
The data provider is trying to pass 0 parameters but the method app.csas.testcases.participanthomepage.validate_participanthomepage#Validate_Employment_Status_As_Active_Or_Terminated takes 2 and TestNG is unable in inject a suitable object">
      <![CDATA[org.testng.TestNGException: 
The data provider is trying to pass 0 parameters but the method app.csas.testcases.participanthomepage.validate_participanthomepage#Validate_Employment_Status_As_Active_Or_Terminated takes 2 and TestNG is unable in inject a suitable object
	at org.testng.internal.Invoker.injectParameters(Invoker.java:1349)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1213)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:768)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1188)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1113)
	at org.testng.TestNG.run(TestNG.java:1025)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
	at org.testng.internal.Invoker.injectParameters(Invoker.java:1347)
	... 17 more
]]>
    </failure>
  </testcase> <!-- Validate_Employment_Status_As_Active_Or_Terminated -->
</testsuite> <!-- Default test -->
